# right from cryptid
[manifest]
version = "1.0.0"
dump_lua = true

# for older smods
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
assembled_string = assembled_string..(type(subpart) == 'string' and subpart or format_ui_value(args.vars[tonumber(subpart[1])]) or 'ERROR')
'''
position = "at"
payload = '''
-- patched by bundles of fun
assembled_string = assembled_string..(type(subpart) == 'string' and subpart or (FoolsPrivilege.process_ordinal and FoolsPrivilege.process_ordinal(subpart[1], args.vars)) or (FoolsPrivilege.pluralize and FoolsPrivilege.pluralize(subpart[1], args.vars)) or format_ui_value(args.vars[tonumber(subpart[1])]) or 'ERROR')
'''
match_indent = true

# for newer smods
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
assembled_string = assembled_string..(type(subpart) == 'string' and subpart or format_ui_value(args.vars[tonumber(subpart[1])]) or 'ERROR')
'''
position = "at"
payload = '''
-- patched by bundles of fun
assembled_string = assembled_string..(type(subpart) == 'string' and subpart or (FoolsPrivilege.process_ordinal and FoolsPrivilege.process_ordinal(subpart[1], args.vars)) or (FoolsPrivilege.pluralize and FoolsPrivilege.pluralize(subpart[1], args.vars)) or format_ui_value(args.vars[tonumber(subpart[1])]) or 'ERROR')
'''
match_indent = true